version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: vcx-teste
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: